services:
  db: 
    image: postgres:15
    container_name: book_postgres_db
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: book_flask_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    # env_file:
    #   - .env