# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.hateoas_links import HateoasLinks  # noqa: F401,E501
from swagger_server import util


class Book(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, isbn: str=None, book_name: str=None, author: str=None, links: HateoasLinks=None):  # noqa: E501
        """Book - a model defined in Swagger

        :param isbn: The isbn of this Book.  # noqa: E501
        :type isbn: str
        :param book_name: The book_name of this Book.  # noqa: E501
        :type book_name: str
        :param author: The author of this Book.  # noqa: E501
        :type author: str
        :param links: The links of this Book.  # noqa: E501
        :type links: HateoasLinks
        """
        self.swagger_types = {
            'isbn': str,
            'book_name': str,
            'author': str,
            'links': HateoasLinks
        }

        self.attribute_map = {
            'isbn': 'isbn',
            'book_name': 'book_name',
            'author': 'author',
            'links': '_links'
        }
        self._isbn = isbn
        self._book_name = book_name
        self._author = author
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'Book':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Book of this Book.  # noqa: E501
        :rtype: Book
        """
        return util.deserialize_model(dikt, cls)

    @property
    def isbn(self) -> str:
        """Gets the isbn of this Book.


        :return: The isbn of this Book.
        :rtype: str
        """
        return self._isbn

    @isbn.setter
    def isbn(self, isbn: str):
        """Sets the isbn of this Book.


        :param isbn: The isbn of this Book.
        :type isbn: str
        """

        self._isbn = isbn

    @property
    def book_name(self) -> str:
        """Gets the book_name of this Book.


        :return: The book_name of this Book.
        :rtype: str
        """
        return self._book_name

    @book_name.setter
    def book_name(self, book_name: str):
        """Sets the book_name of this Book.


        :param book_name: The book_name of this Book.
        :type book_name: str
        """

        self._book_name = book_name

    @property
    def author(self) -> str:
        """Gets the author of this Book.


        :return: The author of this Book.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this Book.


        :param author: The author of this Book.
        :type author: str
        """

        self._author = author

    @property
    def links(self) -> HateoasLinks:
        """Gets the links of this Book.


        :return: The links of this Book.
        :rtype: HateoasLinks
        """
        return self._links

    @links.setter
    def links(self, links: HateoasLinks):
        """Sets the links of this Book.


        :param links: The links of this Book.
        :type links: HateoasLinks
        """

        self._links = links
