# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BooksBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, isbn: str=None, book_name: str=None, author: str=None):  # noqa: E501
        """BooksBody - a model defined in Swagger

        :param isbn: The isbn of this BooksBody.  # noqa: E501
        :type isbn: str
        :param book_name: The book_name of this BooksBody.  # noqa: E501
        :type book_name: str
        :param author: The author of this BooksBody.  # noqa: E501
        :type author: str
        """
        self.swagger_types = {
            'isbn': str,
            'book_name': str,
            'author': str
        }

        self.attribute_map = {
            'isbn': 'isbn',
            'book_name': 'book_name',
            'author': 'author'
        }
        self._isbn = isbn
        self._book_name = book_name
        self._author = author

    @classmethod
    def from_dict(cls, dikt) -> 'BooksBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The books_body of this BooksBody.  # noqa: E501
        :rtype: BooksBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def isbn(self) -> str:
        """Gets the isbn of this BooksBody.


        :return: The isbn of this BooksBody.
        :rtype: str
        """
        return self._isbn

    @isbn.setter
    def isbn(self, isbn: str):
        """Sets the isbn of this BooksBody.


        :param isbn: The isbn of this BooksBody.
        :type isbn: str
        """
        if isbn is None:
            raise ValueError("Invalid value for `isbn`, must not be `None`")  # noqa: E501

        self._isbn = isbn

    @property
    def book_name(self) -> str:
        """Gets the book_name of this BooksBody.


        :return: The book_name of this BooksBody.
        :rtype: str
        """
        return self._book_name

    @book_name.setter
    def book_name(self, book_name: str):
        """Sets the book_name of this BooksBody.


        :param book_name: The book_name of this BooksBody.
        :type book_name: str
        """
        if book_name is None:
            raise ValueError("Invalid value for `book_name`, must not be `None`")  # noqa: E501

        self._book_name = book_name

    @property
    def author(self) -> str:
        """Gets the author of this BooksBody.


        :return: The author of this BooksBody.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this BooksBody.


        :param author: The author of this BooksBody.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author
