# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BooksIsbnBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, book_name: str=None, author: str=None):  # noqa: E501
        """BooksIsbnBody - a model defined in Swagger

        :param book_name: The book_name of this BooksIsbnBody.  # noqa: E501
        :type book_name: str
        :param author: The author of this BooksIsbnBody.  # noqa: E501
        :type author: str
        """
        self.swagger_types = {
            'book_name': str,
            'author': str
        }

        self.attribute_map = {
            'book_name': 'book_name',
            'author': 'author'
        }
        self._book_name = book_name
        self._author = author

    @classmethod
    def from_dict(cls, dikt) -> 'BooksIsbnBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The books_isbn_body of this BooksIsbnBody.  # noqa: E501
        :rtype: BooksIsbnBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def book_name(self) -> str:
        """Gets the book_name of this BooksIsbnBody.


        :return: The book_name of this BooksIsbnBody.
        :rtype: str
        """
        return self._book_name

    @book_name.setter
    def book_name(self, book_name: str):
        """Sets the book_name of this BooksIsbnBody.


        :param book_name: The book_name of this BooksIsbnBody.
        :type book_name: str
        """

        self._book_name = book_name

    @property
    def author(self) -> str:
        """Gets the author of this BooksIsbnBody.


        :return: The author of this BooksIsbnBody.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this BooksIsbnBody.


        :param author: The author of this BooksIsbnBody.
        :type author: str
        """

        self._author = author
