# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.hateoas_links import HateoasLinks  # noqa: F401,E501
from swagger_server import util


class Copy(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, copy_id: str=None, status: str=None, links: HateoasLinks=None):  # noqa: E501
        """Copy - a model defined in Swagger

        :param copy_id: The copy_id of this Copy.  # noqa: E501
        :type copy_id: str
        :param status: The status of this Copy.  # noqa: E501
        :type status: str
        :param links: The links of this Copy.  # noqa: E501
        :type links: HateoasLinks
        """
        self.swagger_types = {
            'copy_id': str,
            'status': str,
            'links': HateoasLinks
        }

        self.attribute_map = {
            'copy_id': 'copy_id',
            'status': 'status',
            'links': '_links'
        }
        self._copy_id = copy_id
        self._status = status
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'Copy':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Copy of this Copy.  # noqa: E501
        :rtype: Copy
        """
        return util.deserialize_model(dikt, cls)

    @property
    def copy_id(self) -> str:
        """Gets the copy_id of this Copy.


        :return: The copy_id of this Copy.
        :rtype: str
        """
        return self._copy_id

    @copy_id.setter
    def copy_id(self, copy_id: str):
        """Sets the copy_id of this Copy.


        :param copy_id: The copy_id of this Copy.
        :type copy_id: str
        """

        self._copy_id = copy_id

    @property
    def status(self) -> str:
        """Gets the status of this Copy.


        :return: The status of this Copy.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Copy.


        :param status: The status of this Copy.
        :type status: str
        """

        self._status = status

    @property
    def links(self) -> HateoasLinks:
        """Gets the links of this Copy.


        :return: The links of this Copy.
        :rtype: HateoasLinks
        """
        return self._links

    @links.setter
    def links(self, links: HateoasLinks):
        """Sets the links of this Copy.


        :param links: The links of this Copy.
        :type links: HateoasLinks
        """

        self._links = links
