# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HateoasLinks(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _self: str=None, create: str=None, update: str=None, delete: str=None, list: str=None):  # noqa: E501
        """HateoasLinks - a model defined in Swagger

        :param _self: The _self of this HateoasLinks.  # noqa: E501
        :type _self: str
        :param create: The create of this HateoasLinks.  # noqa: E501
        :type create: str
        :param update: The update of this HateoasLinks.  # noqa: E501
        :type update: str
        :param delete: The delete of this HateoasLinks.  # noqa: E501
        :type delete: str
        :param list: The list of this HateoasLinks.  # noqa: E501
        :type list: str
        """
        self.swagger_types = {
            '_self': str,
            'create': str,
            'update': str,
            'delete': str,
            'list': str
        }

        self.attribute_map = {
            '_self': 'self',
            'create': 'create',
            'update': 'update',
            'delete': 'delete',
            'list': 'list'
        }
        self.__self = _self
        self._create = create
        self._update = update
        self._delete = delete
        self._list = list

    @classmethod
    def from_dict(cls, dikt) -> 'HateoasLinks':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HateoasLinks of this HateoasLinks.  # noqa: E501
        :rtype: HateoasLinks
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _self(self) -> str:
        """Gets the _self of this HateoasLinks.

        Link to the current resource  # noqa: E501

        :return: The _self of this HateoasLinks.
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self: str):
        """Sets the _self of this HateoasLinks.

        Link to the current resource  # noqa: E501

        :param _self: The _self of this HateoasLinks.
        :type _self: str
        """

        self.__self = _self

    @property
    def create(self) -> str:
        """Gets the create of this HateoasLinks.

        Link to create a new resource  # noqa: E501

        :return: The create of this HateoasLinks.
        :rtype: str
        """
        return self._create

    @create.setter
    def create(self, create: str):
        """Sets the create of this HateoasLinks.

        Link to create a new resource  # noqa: E501

        :param create: The create of this HateoasLinks.
        :type create: str
        """

        self._create = create

    @property
    def update(self) -> str:
        """Gets the update of this HateoasLinks.

        Link to update the resource  # noqa: E501

        :return: The update of this HateoasLinks.
        :rtype: str
        """
        return self._update

    @update.setter
    def update(self, update: str):
        """Sets the update of this HateoasLinks.

        Link to update the resource  # noqa: E501

        :param update: The update of this HateoasLinks.
        :type update: str
        """

        self._update = update

    @property
    def delete(self) -> str:
        """Gets the delete of this HateoasLinks.

        Link to delete the resource  # noqa: E501

        :return: The delete of this HateoasLinks.
        :rtype: str
        """
        return self._delete

    @delete.setter
    def delete(self, delete: str):
        """Sets the delete of this HateoasLinks.

        Link to delete the resource  # noqa: E501

        :param delete: The delete of this HateoasLinks.
        :type delete: str
        """

        self._delete = delete

    @property
    def list(self) -> str:
        """Gets the list of this HateoasLinks.

        Link to list resources  # noqa: E501

        :return: The list of this HateoasLinks.
        :rtype: str
        """
        return self._list

    @list.setter
    def list(self, list: str):
        """Sets the list of this HateoasLinks.

        Link to list resources  # noqa: E501

        :param list: The list of this HateoasLinks.
        :type list: str
        """

        self._list = list
