# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.book import Book  # noqa: F401,E501
from swagger_server.models.hateoas_links import HateoasLinks  # noqa: F401,E501
from swagger_server.models.pagination import Pagination  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, offset: int=None, limit: int=None, total: int=None, items: List[Book]=None, links: HateoasLinks=None, pagination: Pagination=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param offset: The offset of this InlineResponse200.  # noqa: E501
        :type offset: int
        :param limit: The limit of this InlineResponse200.  # noqa: E501
        :type limit: int
        :param total: The total of this InlineResponse200.  # noqa: E501
        :type total: int
        :param items: The items of this InlineResponse200.  # noqa: E501
        :type items: List[Book]
        :param links: The links of this InlineResponse200.  # noqa: E501
        :type links: HateoasLinks
        :param pagination: The pagination of this InlineResponse200.  # noqa: E501
        :type pagination: Pagination
        """
        self.swagger_types = {
            'offset': int,
            'limit': int,
            'total': int,
            'items': List[Book],
            'links': HateoasLinks,
            'pagination': Pagination
        }

        self.attribute_map = {
            'offset': 'offset',
            'limit': 'limit',
            'total': 'total',
            'items': 'items',
            'links': '_links',
            'pagination': 'pagination'
        }
        self._offset = offset
        self._limit = limit
        self._total = total
        self._items = items
        self._links = links
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def offset(self) -> int:
        """Gets the offset of this InlineResponse200.


        :return: The offset of this InlineResponse200.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset: int):
        """Sets the offset of this InlineResponse200.


        :param offset: The offset of this InlineResponse200.
        :type offset: int
        """

        self._offset = offset

    @property
    def limit(self) -> int:
        """Gets the limit of this InlineResponse200.


        :return: The limit of this InlineResponse200.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit: int):
        """Sets the limit of this InlineResponse200.


        :param limit: The limit of this InlineResponse200.
        :type limit: int
        """

        self._limit = limit

    @property
    def total(self) -> int:
        """Gets the total of this InlineResponse200.


        :return: The total of this InlineResponse200.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this InlineResponse200.


        :param total: The total of this InlineResponse200.
        :type total: int
        """

        self._total = total

    @property
    def items(self) -> List[Book]:
        """Gets the items of this InlineResponse200.


        :return: The items of this InlineResponse200.
        :rtype: List[Book]
        """
        return self._items

    @items.setter
    def items(self, items: List[Book]):
        """Sets the items of this InlineResponse200.


        :param items: The items of this InlineResponse200.
        :type items: List[Book]
        """

        self._items = items

    @property
    def links(self) -> HateoasLinks:
        """Gets the links of this InlineResponse200.


        :return: The links of this InlineResponse200.
        :rtype: HateoasLinks
        """
        return self._links

    @links.setter
    def links(self, links: HateoasLinks):
        """Sets the links of this InlineResponse200.


        :param links: The links of this InlineResponse200.
        :type links: HateoasLinks
        """

        self._links = links

    @property
    def pagination(self) -> Pagination:
        """Gets the pagination of this InlineResponse200.


        :return: The pagination of this InlineResponse200.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: Pagination):
        """Sets the pagination of this InlineResponse200.


        :param pagination: The pagination of this InlineResponse200.
        :type pagination: Pagination
        """

        self._pagination = pagination
