# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IsbnCopiesBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, copy_id: str=None, status: str=None):  # noqa: E501
        """IsbnCopiesBody - a model defined in Swagger

        :param copy_id: The copy_id of this IsbnCopiesBody.  # noqa: E501
        :type copy_id: str
        :param status: The status of this IsbnCopiesBody.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'copy_id': str,
            'status': str
        }

        self.attribute_map = {
            'copy_id': 'copy_id',
            'status': 'status'
        }
        self._copy_id = copy_id
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'IsbnCopiesBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The isbn_copies_body of this IsbnCopiesBody.  # noqa: E501
        :rtype: IsbnCopiesBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def copy_id(self) -> str:
        """Gets the copy_id of this IsbnCopiesBody.


        :return: The copy_id of this IsbnCopiesBody.
        :rtype: str
        """
        return self._copy_id

    @copy_id.setter
    def copy_id(self, copy_id: str):
        """Sets the copy_id of this IsbnCopiesBody.


        :param copy_id: The copy_id of this IsbnCopiesBody.
        :type copy_id: str
        """
        if copy_id is None:
            raise ValueError("Invalid value for `copy_id`, must not be `None`")  # noqa: E501

        self._copy_id = copy_id

    @property
    def status(self) -> str:
        """Gets the status of this IsbnCopiesBody.

        Status of the copy (e.g., available, checked out)  # noqa: E501

        :return: The status of this IsbnCopiesBody.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this IsbnCopiesBody.

        Status of the copy (e.g., available, checked out)  # noqa: E501

        :param status: The status of this IsbnCopiesBody.
        :type status: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status
