# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Pagination(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, page: int=None, per_page: int=None, total_pages: int=None, total_items: int=None):  # noqa: E501
        """Pagination - a model defined in Swagger

        :param page: The page of this Pagination.  # noqa: E501
        :type page: int
        :param per_page: The per_page of this Pagination.  # noqa: E501
        :type per_page: int
        :param total_pages: The total_pages of this Pagination.  # noqa: E501
        :type total_pages: int
        :param total_items: The total_items of this Pagination.  # noqa: E501
        :type total_items: int
        """
        self.swagger_types = {
            'page': int,
            'per_page': int,
            'total_pages': int,
            'total_items': int
        }

        self.attribute_map = {
            'page': 'page',
            'per_page': 'perPage',
            'total_pages': 'totalPages',
            'total_items': 'totalItems'
        }
        self._page = page
        self._per_page = per_page
        self._total_pages = total_pages
        self._total_items = total_items

    @classmethod
    def from_dict(cls, dikt) -> 'Pagination':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pagination of this Pagination.  # noqa: E501
        :rtype: Pagination
        """
        return util.deserialize_model(dikt, cls)

    @property
    def page(self) -> int:
        """Gets the page of this Pagination.


        :return: The page of this Pagination.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this Pagination.


        :param page: The page of this Pagination.
        :type page: int
        """
        if page is None:
            raise ValueError("Invalid value for `page`, must not be `None`")  # noqa: E501

        self._page = page

    @property
    def per_page(self) -> int:
        """Gets the per_page of this Pagination.


        :return: The per_page of this Pagination.
        :rtype: int
        """
        return self._per_page

    @per_page.setter
    def per_page(self, per_page: int):
        """Sets the per_page of this Pagination.


        :param per_page: The per_page of this Pagination.
        :type per_page: int
        """
        if per_page is None:
            raise ValueError("Invalid value for `per_page`, must not be `None`")  # noqa: E501

        self._per_page = per_page

    @property
    def total_pages(self) -> int:
        """Gets the total_pages of this Pagination.


        :return: The total_pages of this Pagination.
        :rtype: int
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages: int):
        """Sets the total_pages of this Pagination.


        :param total_pages: The total_pages of this Pagination.
        :type total_pages: int
        """
        if total_pages is None:
            raise ValueError("Invalid value for `total_pages`, must not be `None`")  # noqa: E501

        self._total_pages = total_pages

    @property
    def total_items(self) -> int:
        """Gets the total_items of this Pagination.


        :return: The total_items of this Pagination.
        :rtype: int
        """
        return self._total_items

    @total_items.setter
    def total_items(self, total_items: int):
        """Sets the total_items of this Pagination.


        :param total_items: The total_items of this Pagination.
        :type total_items: int
        """
        if total_items is None:
            raise ValueError("Invalid value for `total_items`, must not be `None`")  # noqa: E501

        self._total_items = total_items
