# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.link import Link  # noqa: F401,E501
from swagger_server import util


class HATEOAS(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, links: List[Link]=None):  # noqa: E501
        """HATEOAS - a model defined in Swagger

        :param links: The links of this HATEOAS.  # noqa: E501
        :type links: List[Link]
        """
        self.swagger_types = {
            'links': List[Link]
        }

        self.attribute_map = {
            'links': '_links'
        }
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'HATEOAS':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HATEOAS of this HATEOAS.  # noqa: E501
        :rtype: HATEOAS
        """
        return util.deserialize_model(dikt, cls)

    @property
    def links(self) -> List[Link]:
        """Gets the links of this HATEOAS.


        :return: The links of this HATEOAS.
        :rtype: List[Link]
        """
        return self._links

    @links.setter
    def links(self, links: List[Link]):
        """Sets the links of this HATEOAS.


        :param links: The links of this HATEOAS.
        :type links: List[Link]
        """

        self._links = links
