# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.hateoas import HATEOAS  # noqa: F401,E501
from swagger_server.models.pagination import Pagination  # noqa: F401,E501
from swagger_server.models.product import Product  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, products: List[Product]=None, pagination: Pagination=None, links: HATEOAS=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param products: The products of this InlineResponse200.  # noqa: E501
        :type products: List[Product]
        :param pagination: The pagination of this InlineResponse200.  # noqa: E501
        :type pagination: Pagination
        :param links: The links of this InlineResponse200.  # noqa: E501
        :type links: HATEOAS
        """
        self.swagger_types = {
            'products': List[Product],
            'pagination': Pagination,
            'links': HATEOAS
        }

        self.attribute_map = {
            'products': 'products',
            'pagination': 'pagination',
            'links': '_links'
        }
        self._products = products
        self._pagination = pagination
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def products(self) -> List[Product]:
        """Gets the products of this InlineResponse200.


        :return: The products of this InlineResponse200.
        :rtype: List[Product]
        """
        return self._products

    @products.setter
    def products(self, products: List[Product]):
        """Sets the products of this InlineResponse200.


        :param products: The products of this InlineResponse200.
        :type products: List[Product]
        """

        self._products = products

    @property
    def pagination(self) -> Pagination:
        """Gets the pagination of this InlineResponse200.


        :return: The pagination of this InlineResponse200.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: Pagination):
        """Sets the pagination of this InlineResponse200.


        :param pagination: The pagination of this InlineResponse200.
        :type pagination: Pagination
        """

        self._pagination = pagination

    @property
    def links(self) -> HATEOAS:
        """Gets the links of this InlineResponse200.


        :return: The links of this InlineResponse200.
        :rtype: HATEOAS
        """
        return self._links

    @links.setter
    def links(self, links: HATEOAS):
        """Sets the links of this InlineResponse200.


        :param links: The links of this InlineResponse200.
        :type links: HATEOAS
        """

        self._links = links
