# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Product(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, product_name: str=None, product_code: int=None, quantity: int=None):  # noqa: E501
        """Product - a model defined in Swagger

        :param id: The id of this Product.  # noqa: E501
        :type id: int
        :param product_name: The product_name of this Product.  # noqa: E501
        :type product_name: str
        :param product_code: The product_code of this Product.  # noqa: E501
        :type product_code: int
        :param quantity: The quantity of this Product.  # noqa: E501
        :type quantity: int
        """
        self.swagger_types = {
            'id': int,
            'product_name': str,
            'product_code': int,
            'quantity': int
        }

        self.attribute_map = {
            'id': 'id',
            'product_name': 'productName',
            'product_code': 'productCode',
            'quantity': 'quantity'
        }
        self._id = id
        self._product_name = product_name
        self._product_code = product_code
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'Product':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Product of this Product.  # noqa: E501
        :rtype: Product
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Product.


        :return: The id of this Product.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Product.


        :param id: The id of this Product.
        :type id: int
        """

        self._id = id

    @property
    def product_name(self) -> str:
        """Gets the product_name of this Product.


        :return: The product_name of this Product.
        :rtype: str
        """
        return self._product_name

    @product_name.setter
    def product_name(self, product_name: str):
        """Sets the product_name of this Product.


        :param product_name: The product_name of this Product.
        :type product_name: str
        """

        self._product_name = product_name

    @property
    def product_code(self) -> int:
        """Gets the product_code of this Product.


        :return: The product_code of this Product.
        :rtype: int
        """
        return self._product_code

    @product_code.setter
    def product_code(self, product_code: int):
        """Sets the product_code of this Product.


        :param product_code: The product_code of this Product.
        :type product_code: int
        """

        self._product_code = product_code

    @property
    def quantity(self) -> int:
        """Gets the quantity of this Product.


        :return: The quantity of this Product.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this Product.


        :param quantity: The quantity of this Product.
        :type quantity: int
        """

        self._quantity = quantity
