# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.link import Link  # noqa: F401,E501
from swagger_server.models.product import Product  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, product: Product=None, links: List[Link]=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param product: The product of this InlineResponse2001.  # noqa: E501
        :type product: Product
        :param links: The links of this InlineResponse2001.  # noqa: E501
        :type links: List[Link]
        """
        self.swagger_types = {
            'product': Product,
            'links': List[Link]
        }

        self.attribute_map = {
            'product': 'product',
            'links': '_links'
        }
        self._product = product
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def product(self) -> Product:
        """Gets the product of this InlineResponse2001.


        :return: The product of this InlineResponse2001.
        :rtype: Product
        """
        return self._product

    @product.setter
    def product(self, product: Product):
        """Sets the product of this InlineResponse2001.


        :param product: The product of this InlineResponse2001.
        :type product: Product
        """

        self._product = product

    @property
    def links(self) -> List[Link]:
        """Gets the links of this InlineResponse2001.


        :return: The links of this InlineResponse2001.
        :rtype: List[Link]
        """
        return self._links

    @links.setter
    def links(self, links: List[Link]):
        """Sets the links of this InlineResponse2001.


        :param links: The links of this InlineResponse2001.
        :type links: List[Link]
        """

        self._links = links
