# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProductInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, product_name: str=None, product_code: int=None, quantity: int=None):  # noqa: E501
        """ProductInput - a model defined in Swagger

        :param product_name: The product_name of this ProductInput.  # noqa: E501
        :type product_name: str
        :param product_code: The product_code of this ProductInput.  # noqa: E501
        :type product_code: int
        :param quantity: The quantity of this ProductInput.  # noqa: E501
        :type quantity: int
        """
        self.swagger_types = {
            'product_name': str,
            'product_code': int,
            'quantity': int
        }

        self.attribute_map = {
            'product_name': 'productName',
            'product_code': 'productCode',
            'quantity': 'quantity'
        }
        self._product_name = product_name
        self._product_code = product_code
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'ProductInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductInput of this ProductInput.  # noqa: E501
        :rtype: ProductInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def product_name(self) -> str:
        """Gets the product_name of this ProductInput.


        :return: The product_name of this ProductInput.
        :rtype: str
        """
        return self._product_name

    @product_name.setter
    def product_name(self, product_name: str):
        """Sets the product_name of this ProductInput.


        :param product_name: The product_name of this ProductInput.
        :type product_name: str
        """
        if product_name is None:
            raise ValueError("Invalid value for `product_name`, must not be `None`")  # noqa: E501

        self._product_name = product_name

    @property
    def product_code(self) -> int:
        """Gets the product_code of this ProductInput.


        :return: The product_code of this ProductInput.
        :rtype: int
        """
        return self._product_code

    @product_code.setter
    def product_code(self, product_code: int):
        """Sets the product_code of this ProductInput.


        :param product_code: The product_code of this ProductInput.
        :type product_code: int
        """
        if product_code is None:
            raise ValueError("Invalid value for `product_code`, must not be `None`")  # noqa: E501

        self._product_code = product_code

    @property
    def quantity(self) -> int:
        """Gets the quantity of this ProductInput.


        :return: The quantity of this ProductInput.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this ProductInput.


        :param quantity: The quantity of this ProductInput.
        :type quantity: int
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity
